[project]
name = "virtuale-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=46.0.5",
    "httpx>=0.28.1",
    "playwright>=1.58.0",
    "groq>=0.11.0",
    "python-dotenv>=1.0.0",
]
